//! The Minecraft map: a world generated by MinecraftOSS, played on top of a
//! small IW4 map loaded only for the shared weapon, body and menu content.
//! None of that map's world is shown or collided with.
use asset_transport::{GamesRoot, ZoneFile};

pub const ZONE: &str = "minecraft:overworld";
const PROXY_ZONE: &str = "iw4:mp_rust";
/// The map whose level script the Minecraft world runs.
pub const PROXY_MAP: &str = "mp_rust";

pub fn is_minecraft(zone: &str) -> bool {
    zone.eq_ignore_ascii_case(ZONE)
}

/// Whether a load's zone, with or without its content namespace, is the
/// Minecraft map.
pub fn is_minecraft_load(zone: &str) -> bool {
    is_minecraft(zone) || zone.split_once(':').is_some_and(|(_, rest)| is_minecraft(rest))
}

/// Where the world's Minecraft files are: a MinecraftOSS checkout named by
/// `MINECRAFTOSS_ROOT`, else the files fetched from Mojang once they are in.
pub fn root() -> Option<std::path::PathBuf> {
    if let Some(root) = std::env::var_os("MINECRAFTOSS_ROOT").map(std::path::PathBuf::from)
        && root.join("datapacks").is_dir()
    {
        return Some(root);
    }
    crate::minecraft_setup::ready()
}

/// Starts fetching Minecraft's files from Mojang when nothing supplies them.
pub fn prepare() {
    if root().is_none() {
        crate::minecraft_setup::begin();
    }
}

pub fn find_zone_file(root_dir: &GamesRoot, zone: &str) -> Result<ZoneFile, String> {
    if !is_minecraft_load(zone) {
        return asset_transport::find_zone_file(root_dir, zone);
    }
    let checkout = match root() {
        Some(root) => root,
        None => {
            // A first run straight into this map waits for Mojang's files.
            crate::minecraft_setup::begin();
            diag::info!(World, "Minecraft map: waiting for Minecraft's files from Mojang");
            // Briefly: a load held much longer does not come back cleanly,
            // and the fetch carries on for the next try.
            crate::minecraft_setup::wait(std::time::Duration::from_secs(90))
                .ok_or_else(crate::minecraft_setup::status)?
        }
    };
    let mut proxy = asset_transport::find_zone_file(root_dir, PROXY_ZONE)?;
    proxy.zone_name = ZONE.to_owned();
    proxy.alias_note = Some(format!("Minecraft world from {}", checkout.display()));
    Ok(proxy)
}

/// The installed map packs, with the Minecraft world as a pack of its own
/// when the map it stands in for is installed.
pub fn list_mp_map_packs(root_dir: &GamesRoot) -> Vec<asset_transport::MapPack> {
    prepare();
    let mut packs = asset_transport::list_mp_map_packs(root_dir);
    if asset_transport::find_zone_file(root_dir, PROXY_ZONE).is_ok() {
        packs.push(asset_transport::MapPack {
            label: "Minecraft".to_owned(),
            maps: vec![ZONE.to_owned()],
        });
    }
    packs
}

pub fn list_mp_maps(root_dir: &GamesRoot) -> Vec<String> {
    let mut maps = asset_transport::list_mp_maps(root_dir);
    // Listed before Mojang's files are in: loading it waits for them.
    prepare();
    if asset_transport::find_zone_file(root_dir, PROXY_ZONE).is_ok() {
        maps.push(ZONE.to_owned());
    }
    maps.sort();
    maps.dedup();
    maps
}
