#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum CacHostSlot {
    Primary,
    Secondary,
    Lethal,
    Tactical,
    Perk1,
    Perk2,
    Perk3,
    Deathstreak,
}

pub fn cac_host_roster(row: CacHostSlot) -> &'static [&'static str] {
    match row {
        CacHostSlot::Primary => &[
            "m4_mp",
            "famas_mp",
            "scar_mp",
            "tar21_mp",
            "fal_mp",
            "m16_mp",
            "masada_mp",
            "fn2000_mp",
            "ak47_mp",
            "mp5k_mp",
            "uzi_mp",
            "p90_mp",
            "kriss_mp",
            "ump45_mp",
            "rpd_mp",
            "sa80_mp",
            "mg4_mp",
            "m240_mp",
            "aug_mp",
            "barrett_mp",
            "cheytac_mp",
            "wa2000_mp",
            "m21_mp",
            "riotshield_mp",
        ],
        CacHostSlot::Secondary => &[
            "glock_mp",
            "beretta393_mp",
            "pp2000_mp",
            "tmp_mp",
            "ranger_mp",
            "model1887_mp",
            "striker_mp",
            "aa12_mp",
            "m1014_mp",
            "spas12_mp",
            "usp_mp",
            "beretta_mp",
            "deserteagle_mp",
            "coltanaconda_mp",
            "at4_mp",
            "rpg_mp",
            "stinger_mp",
            "javelin_mp",
        ],
        CacHostSlot::Lethal => &[
            "frag_grenade_mp",
            "semtex_mp",
            "throwingknife_mp",
            "claymore_mp",
            "c4_mp",
        ],
        CacHostSlot::Tactical => &[
            "flash_grenade_mp",
            "concussion_grenade_mp",
            "smoke_grenade_mp",
            "flare_mp",
        ],
        CacHostSlot::Perk1 => &[
            "specialty_null",
            "specialty_marathon",
            "specialty_fastreload",
            "specialty_scavenger",
            "specialty_onemanarmy",
            "specialty_bling",
        ],
        CacHostSlot::Perk2 => &[
            "specialty_null",
            "specialty_bulletdamage",
            "specialty_lightweight",
            "specialty_hardline",
            "specialty_coldblooded",
            "specialty_explosivedamage",
        ],
        CacHostSlot::Perk3 => &[
            "specialty_null",
            "specialty_extendedmelee",
            "specialty_bulletaccuracy",
            "specialty_localjammer",
            "specialty_heartbreaker",
            "specialty_detectexplosive",
            "specialty_pistoldeath",
        ],
        CacHostSlot::Deathstreak => &[
            "specialty_null",
            "specialty_grenadepulldeath",
            "specialty_c4death",
            "specialty_combathigh",
            "specialty_finalstand",
            "specialty_copycat",
        ],
    }
}
